version: '3'

tasks:
  build:
    cmds:
      - cmd: go build -ldflags="-H windowsgui" -o splitters.exe .
        platforms: [windows]
      - cmd: go build -o splitters .
        platforms: [linux]
  run:
    cmds:
      - go run .
